theme: jekyll-theme-minimal
title: The Star System
description: An ivestigation of actor's impact on movie ratings
show_downloads: True
navigation:
  - title: Home
    url: README
  - title: Introduction
    url: introduction
  - title: Rich-get-Richer Mechanism
    url: rgr
  - title: Observational Study
    url: observational_study
