theme: jekyll-theme-minimal
title: The Star System
description: A template website for ADA
show_downloads: True
navigation:
  - title: Home
    url: README
  - title: Example
    url: example
  - title: Observational study
    url: observational_study
